name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-and-test:
    name: Check, Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Rustfmt Check
        run: cargo fmt --all -- --check

      - name: Clippy Linter
        run: cargo clippy --all-targets -- -D warnings

      - name: Run Tests
        run: cargo test --all-targets --verbose

      - name: Build Release
        run: cargo build --release --verbose
